### ISSUE TITLE
clarification with cocoapods

### ISSUE THREAD

**Issue by johndpope** [toshi0383/xcconfig-extractor#12]
I run the xcconfig-extractor and it successfully rips out settings to Configuration folder.

It seems that cocoapods overrides all configs with it's own files. 
Perhaps need to have cocoapods optionally adopt this library to strip out settings.
Is there any way to have the new config files piggy back off the pod settings? (inherit from)
<img width="709" alt="screen shot 2017-05-12 at 9 45 18 am" src="https://cloud.githubusercontent.com/assets/289994/26000631/bb64529e-36f7-11e7-91a9-1c6c0bf8066b.png">

**Comment by toshi0383** [comment]
Hi @johndpope ,
By default `--include-existing` option is enabled, so if you have existing xcconfigs configured on Xcode, then you should see `#include` lines in generated xcconfigs. You just need to simply add generated xcconfigs to your project, and replace the Configurations manually.
Please follow [README](https://github.com/toshi0383/xcconfig-extractor#build-setting-validation) for Build Settings Validation. 

In my case I had CocoaPods' xcconfigs setup as well, and it has been working fine after applying xcconfig-extractor.👌
Let me know if you encountered any issues related to CocoaPods. I'd be happy to dig into it.

**Comment by johndpope** [comment]
I'll have another crack thanks. Did you run pod update ? I worry it will be hard to maintain. I know the dudes at artsy and think this code is fantastic and worth considering to merge into cocoa pods.

**Comment by toshi0383** [comment]
@johndpope 
[`pod update` preserves existing xcconfig](https://github.com/CocoaPods/CocoaPods/blob/7bef87f95b85ee31ce6ad04e7d14645965ab86bf/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb#L91), so I'd say it would be easy to maintain.😉

**Comment by toshi0383** [comment]
By the way I'm working on [pbxproj parser](https://github.com/toshi0383/Pbxproj) right now, so adding xcconfig to xcodeproj will be handled automatically in near future.

**Comment by toshi0383** [comment]
> adding xcconfig to xcodeproj will be handled automatically in near future

Done in #13 .

**Comment by toshi0383** [comment]
Closing this.
Please feel free to reopen this issue anytime. 😉

**Comment by johndpope** [comment]
nice.

**Comment by johndpope** [comment]
https://github.com/johndpope/xcodeproj FYI
