### ISSUE TITLE
Migrate Swift4

### ISSUE THREAD

**Issue by toshi0383** [toshi0383/xcconfig-extractor#18]

**Comment by mickamy** [comment]
Any progress on this?
Or should I ask is this repo still maintained?

**Comment by toshi0383** [comment]
Hi @mickamy thanks for pinging.😀
I've been busy with other oss projects and I will be able to get going with this at least later this year.

I was refactoring using https://github.com/tuist/xcodeproj instead of my own lib (https://github.com/toshi0383/AsciiPlistParser), but it was a while ago, so looks like the branch is already outdated.
I saw you forking this repo, so you can work on this if you want. Happy to accept PRs.👍

I believe you can still install the binary directly as noted in README, but let me know if you have any issue.

**Comment by toshi0383** [comment]
Done in #20 with **huge internal breaking changes** and released in `0.5.0`.
Simple cases are ensured to work with unit tests, but not battle tested yet.
Please expect minor or major bugs and post issues or pull-requests for any problems😉
