### ISSUE TITLE
Outdated installer

### ISSUE THREAD

**Issue by aplr** [toshi0383/xcconfig-extractor#25]
Hi, I just wanted to install the newest version of this tool using your install script, but it still installs v0.5 instead of v0.6.1, since it is the latest tag referenced to a release.

**Comment by toshi0383** [comment]
Hi @aplr !
Yea thought about it, but left it as is, since there is no difference between them in functionality.
Do you have any problems on installing?

Also I believe Swift5 doesn’t allow embedded stdlib in executable anymore, so I guess I have to deprecate binary install in future release.🙄

**Comment by aplr** [comment]
Oh ok, fine. I don't have any problems installing 0.5, but as 0.5 gives me an error when extracting from my Xcode 11 project I need 0.6, which I've installed manually for now.

**Comment by toshi0383** [comment]
Ah you’re right. Xcode11 has breaking change in pbxproj structure in terms of SwiftPM.
I will update README.👌

**Comment by toshi0383** [comment]
Fixed in 59651fb . Thank you for reporting @aplr  ! 🙌
