### ISSUE TITLE
Failed to parse xcodeproj

### ISSUE THREAD

**Issue by arusu0629** [toshi0383/xcconfig-extractor#26]
Dear @toshi0383 

Your library is very useful and I've tried to use it.
The following error has occurred.
Can you advise me on what to do, Thanks.

![スクリーンショット 2020-08-18 11 34 28](https://user-images.githubusercontent.com/5705360/90463909-16d1d780-e147-11ea-8fe9-194f675c76ca.png)

### Environment
- Xcode 11.6
- Swift 5.2.4
- xcconfig-extractor 0.5.0

**Comment by toshi0383** [comment]
Hi @arusu0629 👋🏻
Updated codebase in 1ace8d0938b23044fbb3677c9ef8a3cfc47d3798 .
Could you try again with that version?

**Comment by arusu0629** [comment]
Thank you for reply @toshi0383 
I tried 1ace8d0 version, worked well. 

However, We've got a massive diff between before and after.
How should I respond?

```
$ xcodebuild -showBuildSettings -configuration Release > before
$ # apply xcconfig-extractor
$ xcodebuild -showBuildSettings -configuration Release > after
$ diff before after # should prints nothing!
```

**Comment by toshi0383** [comment]
That's something we have to spend time to debug. I don't have much time these days, so PR is welcomed!😀

Original parsing issue is resolved, so closing this one👌 Thanks for heads-up!
